######################################################################
# Automatically generated by qmake (2.01a) lun sep 22 11:50:23 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CPostgreSQL.h
SOURCES += CPostgreSQL.cpp main.cpp

QT += sql